# https://starship.rs/config

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ $username ](fg:#090c0c bg:#a3aed2)\
[](fg:#a3aed2 bg:#52b786)\
$hostname\
[](fg:#52b786 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$aws\
$buf\
$c\
$conda\
$crystal\
$dart\
$docker_context\
$elixir\
$elm\
$fennel\
$golang\
$haskell\
$haxe\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$zig\
[](fg:#212736 bg:#1d2230)\
$time\
[](fg:#1d2230)\
\n$character"""

[username]
style_user  = 'bg:#a3aed2 fg:#090c0c'
style_root  = 'bg:#a3aed2 fg:#0b0e0e'
format      = '[$user]($style)'
disabled    = false
show_always = true
# aliases   = { "tadinada" = "Sathya" } // Add aliases for usernames

[directory]
read_only = " 󰌾"
truncate_to_repo = false
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"

[time]
disabled    = false
time_format = "%R"                                       # Hour:Minute Format (24-hour)
style       = "bg:#1d2230"
format      = '[[   $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
success_symbol  = '[❯](green)'
error_symbol    = '[❯](red)'

[aws]
symbol  = "  "
style   = "bg:#212736"
format  = '[[ $symbol ($profile )](fg:#769ff0 bg:#212736)]($style)'

[buf]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[c]
symbol  = ""
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[conda]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[crystal]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[dart]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[docker_context]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[elixir]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[elm]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[fennel]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[fossil_branch]
symbol  = " "

[git_branch]
symbol  = " "
style   = "bg:#394260"
format  = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style   = "bg:#394260"
format  = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[git_commit]
tag_symbol  = '  '

[golang]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[gradle]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[guix_shell]
symbol  = " "

[haskell]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[haxe]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[hg_branch]
symbol  = " "

[hostname]
ssh_symbol  = " "
ssh_only    = true
style       = 'bg:#52b786 fg:#e3e5e5'
format      = '[ $hostname ]($style)'

[java]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[julia]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[kotlin]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[lua]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[memory_usage]
symbol  = "󰍛 "

[meson]
symbol  = "󰔷 "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[nim]
symbol  = "󰆥 "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[nix_shell]
symbol  = " "

[nodejs]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[ocaml]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[os]
disabled = false
style = 'bg:#a3aed2 fg:#090c0c'

[os.symbols]
Alpaquita           = " "
Alpine              = " "
AlmaLinux           = " "
Amazon              = " "
Android             = " "
Artix               = " "
Arch                = " "
CentOS              = " "
Debian              = " "
Emscripten          = " "
DragonFly           = " "
EndeavourOS         = " "
Fedora              = " "
FreeBSD             = " "
Garuda              = "󰛓 "
Gentoo              = " "
HardenedBSD         = "󰞌 "
Illumos             = "󰈸 "
Kali                = " "
Linux               = " "
Mabox               = " "
Macos               = " "
Manjaro             = " "
Mariner             = " "
MidnightBSD         = " "
Mint                = " "
NetBSD              = " "
NixOS               = " "
OpenBSD             = "󰈺 "
openSUSE            = " "
OracleLinux         = "󰌷 "
Pop                 = " "
Raspbian            = " "
Redhat              = " "
RedHatEnterprise    = " "
RockyLinux          = " "
Redox               = "󰀘 "
Solus               = "󰠳 "
SUSE                = " "
Ubuntu              = " "
Unknown             = " "
Void                = " "
Windows             = "󰍲 "

[package]
symbol  = "󰏗 "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[perl]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[pijul_channel]
symbol  = " "

[python]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[rlang]
symbol  = "󰟔 "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[ruby]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[scala]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[swift]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'

[zig]
symbol  = " "
style   = "bg:#212736"
format  = '[[ $symbol ($version )](fg:#769ff0 bg:#212736)]($style)'
